config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: 'users/passwords'
  }
  
  # ゲストログイン
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  get "users/show" => "users#show"
  root 'pages#index'
  

  resources :posts
  resources :users

  resources :relationships,only: [:create, :destroy]
  resources :graphs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  
  validates :today_mood, presence: true
  validates :content, length: { maximum: 30 } 
  
  # 1日1回迄の投稿制限
  validate :diary_limit, on: :create
  
  # 今日の感情表示
  enum today_mood: { ◯: 0, △: 1, ×: 2 }
  
  private
  
  # 1日1回迄の投稿制限
  def diary_limit
    if Post.where(user_id: user.id).where("start_time > ?", Date.today).present?
      errors.add(:content,"の投稿は1日1回までです")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  
  # ユーザーとの投稿アソシエーション
  has_many :posts, dependent: :destroy
  
  # ゲストログイン機能
  def self.guest
    find_or_create_by!(name: 'ゲスト', email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end
  
  # ユーザーランダムIDの生成
  generate_public_uid

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    posts_path
  end

  private
      def sign_in_required
          redirect_to new_user_session_url unless user_signed_in?
      end
  
  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController
  def index
    @post = Post.where(id: params[:id])
    @user = User.where(id: params[:id])
  end
end

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController
 def index
   @users = User.where.not(id: current_user.id)
   @user  = User.find_by(id: params[:name])
   @posts = Post.all.includes(:user).where(user_id: @users)
  end
end

app/controllers/graphs_controller.rb
class GraphsController < ApplicationController
  
  def index
    @posts = Post.all
    @posts = Post.where(user_id: current_user.id)
    
    # グラフ
    @day_list = {}.tap do |result|
      @posts.each do |post|
        # 今日の日付と値に対する処理
        Rails.logger.debug post.today_mood
        # 投稿が一致するものを複数から探す
        result[post.created_at.to_date] = case post.today_mood
                                  when '◯'
                                    3
                                  when '△'
                                    2
                                  when '×'
                                    1
                                  end
      end
    end
    Rails.logger.debug @day_list
    # パラメーターでdate月を取得した時の処理
    @month_days =  if params[:date].present?
    # 次の月・前の月　date を Date._parseでTimeオブジェクトに変換
      @month = Time.parse(params[:date] + "01")
    # 配列に変換し月の日付を取得
      (@month.beginning_of_month.to_datetime..@month.end_of_month.to_datetime).to_a
    else
      # 当月
      @month = Time.current.to_date
      (@month.beginning_of_month.to_datetime..@month.end_of_month.to_datetime).to_a
    end
    
    # 評価比較　当月の始まりと終わりを入れて当月のみ取得
    @maru = @posts.where(today_mood: "◯", created_at: @month.beginning_of_month..@month.end_of_month)
    @sankaku = @posts.where(today_mood: "△", created_at: @month.beginning_of_month..@month.end_of_month)
    @batu = @posts.where(today_mood: "×", created_at: @month.beginning_of_month..@month.end_of_month)
    
    
    @post_by_day = {}.tap do |result|
      @month_days.each do |d|
        result[d] = @day_list[d] ? @day_list[d] : 0
      end
    end
    
    # 日付のラベル　javascriptの変数として渡す
    @chartlabels = @post_by_day.map(&:first).to_json.html_safe
    @chartdatas = @post_by_day.map(&:second)

    
     # 折線グラフ
    # @cumulative = []
    # sum=0
    # @chartdatas.each do |a|
    #   sum = sum + a
    #   @cumulative<<sum
    # end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :sign_in_required, only: [:show]
  
  def index;end
  
  # ゲストログイン
  def guest_sign_in
    user = User.find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :correct_user, only: [:edit, :update, :destroy, :show]

  def index
    @posts = Post.all
    @posts = Post.where(user_id: current_user.id)
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    @post[:start_time] = DateTime.current
    respond_to do |format|
      format.js do
        @post.save
      end
    end
  end

  def show
    respond_to do |format|
      format.js
    end
  end

  def edit
    respond_to do |format|
      format.js
    end  
  end

  def update
    if @post.update(post_params)
      redirect_to posts_path,  notice: t('defaults.message.update')
    else
      flash.now['alert'] = t('defaults.message.not_updated')
      render :edit
    end
  end
  
  def destroy
    @post.destroy!
    redirect_to posts_path, alert: t('defaults.message.deleted')
  end

  private
  
def correct_user
  @post = current_user.posts.find_by(id: params[:id])
  unless @post
    redirect_to posts_path
  end
end

  def post_params
    params.require(:post).permit(:content, :today_mood, :start_time)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    @user = User.find_by(id: params[:relationship][:following_id])
    current_user.follow!(@user)
    redirect_to followers_path(@user)
  end

  def destroy
    @user = Relationship.find(params[:id]).following
    current_user.unfollow!(@user)
    redirect_to followers_path(@user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_action :search
   before_action :correct_user
  
  def index;end

  # ユーザーのプロフィール
  def show
    unless user_signed_in?
    redirect_to user_session_path, alert: t('defaults.message.login')
    end
    @count_posts = current_user.posts.all.count
  end
  
  def search
    @q = User.ransack(params[:q])
  end
  
  private
  
  def correct_user
      @users = current_user
    unless @users
      redirect_to posts_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def bootstrap_alert(key)
    case key
    when "alert"
      "danger"
    when "notice"
      "success"
    when "error"
      "danger"
    end
  end
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/following_helper.rb
module FollowingHelper
end

app/helpers/graph_helper.rb
module GraphHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user?(user)
     user == current_user
  end
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= bootstrap_alert(key) %> alert-dismissible fade show">
    <span><%= value %></span>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="footer">
  <nav class="navbar navbar-expand-md">
    © しあわせのものさし 2022 All Rights Reserved.
  </div>
</div>

app/views/layouts/_header.html.erb
<header class="site-header">
  <nav class="navbar navbar-expand-lg">
      <div class="header_logo">
        <%= link_to image_tag("diary.png"), root_path %>
      </div>
    <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#Navber" aria-controls="Navber" aria-expanded="false" aria-label="ナビゲーションの切替">
      <span class="navbar-toggler-icon"></span>
    </button>
      <div class="hamburger">
      </div>
    <div class="openbtn1"><span></span><span></span><span></span></div>
      <nav id="g-nav">
        <div id="g-nav-list">
          <ul class="header-nav">
          <% if user_signed_in? %>
            <li>
              <a class="nav-item">
              <%= link_to '日記', posts_path, class: "nav-link" %>
              </a>
            </li>
            <li>
              <a class="nav-item">
              <%= link_to 'グラフ', graphs_path, class: "nav-link"  %>
              </a>
            </li>
            <li>
              <a class="nav-item">
              <%= link_to 'プロフィール', users_show_path, class: "nav-link"  %>
              </a>
            </li>
            <li>
              <a class="nav-item">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link", data: { confirm: 'ログアウトしますか？' } %>
              </a>
            </li>
          <% else %>
            <a class="nav-item">
              <%= link_to "新規登録", new_user_registration_path, class: "nav-link" %>
            </a>
            <a class="nav-item">
              <%= link_to "ログイン", new_user_session_path, class: "nav-link"  %>
            </a>
            <a class="nav-item">
            <%= link_to '覗いてみる', users_guest_sign_in_path, method: :post, class: "nav-link" %>
            </a>
          <% end %>
        </ul>
      </div>
    </nav>
</header>

<script>
$(".openbtn1").click(function () {
  $(this).toggleClass('active');
    $("#g-nav").toggleClass('panelactive');
});

$("#g-nav a").click(function () {
    $(".openbtn1").removeClass('active');
    $("#g-nav").removeClass('panelactive');
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>DeviseRails6</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <style>@import url('https://fonts.googleapis.com/css2?family=Kosugi+Maru&family=M+PLUS+Rounded+1c:wght@500;800&family=Mochiy+Pop+P+One&family=Potta+One&family=Zen+Kaku+Gothic+New:wght@500&display=swap');</style>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
     <meta charset="utf-8">
     <%= favicon_link_tag('favicon.ico') %>
   <head>
   <body>
      <%= render 'layouts/header' %>
      <%= render 'layouts/flash_messages' %>
　　　<div class="container content">
        <%= yield %>
      </div>
      <%= render 'layouts/footer' %>
  </body>
</html>

<!--フラッシュメッセージの秒数-->
<script>
$(function(){
  $(".alert").fadeOut(4000);
});
</script>

app/views/pages/index.html.erb
<center>
    <div class="main">
      <div class="main-content">
        <div class="font-group">
         <%= image_tag 'toplogo.png', class: 'page-logo', width: '40%', height: '40%' %>
        </div>
        <div class="main-font">
          <h1>しあわせのものさし</h1>
          <h2>自分にとっての「しあわせ」を見つけよう</h2>
          <h3>しあわせのものさしは、日記にしあわせ評価しその理由を書いてもらい、自分のしあわせを可視化するサービスです。</h3>
        </div>
       </div>
      
         <div class="top-loginbtn">
        <div class="buttons">
          <%= link_to 'ログイン', new_user_session_path, class: "login-btn" %></p>
        </div>
        <div class="buttons">
          <%= link_to '新規登録', new_user_registration_path, class: "login-btn" %></p>
        </div>
        <div class="buttons">
          <%= link_to '覗いてみる', users_guest_sign_in_path, method: :post, class: "login-btn" %></p>
        </div>
      </div>
    </div>
    
 
    <div class="main-content-Introduction">
      <p>しあわせのものさしの特徴</p>
    </div>
  
      <div class="main-content-text">
        <div class="box2">
          <div class="main-Heading">
            <p>しあわせを書き出す</p>
          </div>
            <div class="main-content-image">
              <%= image_tag 'diary.png', class: 'page-graphr', width: '70%', height: '70%' %>
            <div class="main-font">
                <p>入力はカンタン。今日の自分のしあわせ振り返ってみてを◯ △ ×で評価。その理由を一行で書き込むだけ</p>
            </div>
          </div>
        </div>
    
        <div class="box2">
          <div class="main-Heading">
            <p>グラフで比較する</p>
          </div>
          <div class="main-content-image">
            <%= image_tag 'graph.png', class: 'page-graph', width: '100%', height: '100%' %>
          <div class="main-font">
            <p>◯ △ ×の数がどの時期に多かったのかパッとみて分かるグラフ付。自分の気分の波を把握することができるよ。</p>
          </div>
        </div>
      </div>
        
        <div class="box2">
          <div class="main-Heading">
            <p>しあわせを比較する</p>
          </div>
          <div class="main-content-image">
            <%= image_tag 'question.png', class: 'page-graph', width: '70%', height: '70%' %>
          <div class="main-font">
            <p>自分のしあわせだった事、そうではなかった事を比較できる機能付。自分にとって
            しあわせになる為に必要だと感じていたことが実はそうでもなかったり、逆に意外な事にしあわせを感じたり。</p>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/pages/show.html.erb
<%= month_calendar do |date| %>
  <%= date %>
<% end %>

<%= link_to '仮日記作成ボタン', new_post_path %>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: '<<'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: '>>'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
            <% week.each do |day| %>
               <%= content_tag :td, class: calendar.td_classes_for(day) do %>
               <div class="day-box1">
                 <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
               </div>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>